<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns="http://tempuri.org/circuito" elementFormDefault="qualified" targetNamespace="http://tempuri.org/circuito" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchuraMedia" />
				<xs:element ref="fechaCarrera" />
				<xs:element ref="horaCarrera" />
				<xs:element ref="vueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="origen" />
				<xs:element ref="ganadorCarrera" />
				<xs:element ref="tiempoGanador" />
				<xs:element ref="clasificadosMundial" />
				<xs:element ref="trazado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitudCircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="anchuraMedia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fechaCarrera" type="xs:string" />
	<xs:element name="horaCarrera" type="xs:string" />
	<xs:element name="vueltas" type="xs:string" />
	<xs:element name="localidad" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:string" />
	<xs:element name="latitud" type="xs:string" />
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ganadorCarrera" type="xs:string" />
	<xs:element name="tiempoGanador" type="xs:string" />
	<xs:element name="clasificadosMundial">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="clasificado" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificado">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="posicion" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="trazado">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia" />
				<xs:element ref="puntoFinal" />
				<xs:element ref="sector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="unidad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoFinal">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="sector" type="xs:string" />
</xs:schema>